development:
  adapter: postgresql
  encoding: unicode
  database: property_management_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: property_management_test
  pool: 5
  username:
  password:


